const carData = [
    {
        brand: 'Audi',
        model: 'A3',
        firstRegistration: '2004.10.18.',
        mileage: 260000,
        fuelType: 'dízel',
        performance: 125,
        cost: 1350000,
        condition: 'jó',
        advertText: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut harum quam omnis facilis aliquam, repellat eveniet pariatur neque voluptates dolor.',
        advertTitle: 'Eladó Audi A3',
        image: './img/audi-a3.jpg',
    },
    {
        brand: 'Hyundai',
        model: 'Atos',
        firstRegistration: '1998.12.10.',
        mileage: 180000,
        fuelType: 'benzin',
        performance: 65,
        cost: 700000,
        condition: 'megfelelő',
        advertText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio aspernatur similique blanditiis officia earum sapiente.',
        advertTitle: 'Eladó Hyundai Atos',
        image: './img/hyundai-atos.jpg',
    },
    {
        brand: 'Kia',
        model: 'Picanto',
        firstRegistration: '2006.02.20.',
        mileage: 170000,
        fuelType: 'benzin',
        performance: 75,
        cost: 980000,
        condition: 'hibátlan',
        advertText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio aspernatur similique blanditiis officia earum sapiente.',
        advertTitle: 'Eladó Kia Picanto',
        image: './img/kia-picanto.jpg',
    },
    {
        brand: 'Lada',
        model: '1200',
        firstRegistration: '1980.06.07.',
        mileage: 60000,
        fuelType: 'benzin',
        performance: 68,
        cost: 1550000,
        condition: 'hibátlan',
        advertText: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, veniam fuga eos corporis sunt alias enim quasi cupiditate. Pariatur eum eligendi veniam distinctio sed!',
        advertTitle: 'Eladó Lada 1200',
        image: './img/lada-1200.jpg',
    },
    {
        brand: 'Mercedes',
        model: 'G250',
        firstRegistration: '2014.03.09.',
        mileage: 48000,
        fuelType: 'dízel',
        performance: 350,
        cost: 6500000,
        condition: 'hibátlan',
        advertText: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, veniam fuga eos corporis sunt alias enim quasi cupiditate. Pariatur eum eligendi veniam distinctio sed!',
        advertTitle: 'Eladó Mercedes G250',
        image: './img/mercedes-g250.jpg',
    },
    {
        brand: 'Range Rover',
        model: 'Evoque',
        firstRegistration: '2016.09.01.',
        mileage: 120000,
        fuelType: 'hybrid',
        performance: 250,
        cost: 5400000,
        condition: 'jó',
        advertText: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, veniam fuga eos corporis sunt alias enim quasi cupiditate. Pariatur eum eligendi veniam distinctio sed!',
        advertTitle: 'Eladó Range Rover Evoque',
        image: './img/rangerover-evoque.jpg',
    },
    {
        brand: 'Toyota',
        model: 'Highlander',
        firstRegistration: '2009.04.08.',
        mileage: 156000,
        fuelType: 'hybrid',
        performance: 236,
        cost: 4750000,
        condition: 'jó',
        advertText: 'Lorem ipsum dolor sit amet consectetur. Ratione, veniam fuga eos enim quasi cupiditate. Pariatur eum eligendi veniam distinctio sed!',
        advertTitle: 'Eladó Toyota Highlander',
        image: './img/toyota-highlander.jpg',
    },
    {
        brand: 'Toyota',
        model: 'Supra',
        firstRegistration: '2018.09.30.',
        mileage: 25000,
        fuelType: 'elektromos',
        performance: 420,
        cost: 9800000,
        condition: 'hibátlan',
        advertText: 'Lorem ipsum dolor sit amet. Ratione, veniam fuga eos corporis sunt alias enim. Pariatur eum eligendi veniam distinctio sed!',
        advertTitle: 'Eladó Toyota Supra',
        image: './img/toyota-supra.jpg',
    },
];

module.exports.carData = carData;